trigger:
- main

pool:
  name: Azure_Devops

stages:
- stage: Build
  jobs:
  - job: FirstJob01
    steps:
    # - bash: echo build FirstJob01
    # - bash: echo $(PipelineLevelVariable)
    # - bash: echo $(Build.BuildNumber)
    # - bash: echo $(Build.BuildId)
    # - bash: echo $(Build.SourceBranchName)
    # - bash: echo $(Build.SourcesDirectory)
    # - bash: echo $(System.DefaultWorkingDirectory)
    # - bash: ls -R $(System.DefaultWorkingDirectory)
    # - bash: echo $(Build.ArtifactStagingDirectory)
    # - bash: java -version
    # - bash: Python --version
    # - bash: nvm --version
    - bash: ls -R $(Build.ArtifactStagingDirectory)

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -R $(Build.ArtifactStagingDirectory)


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'


# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
